version: "3"
services:
  web-app:
    build:
      context: ../.
      dockerfile: src/WebApp/Dockerfile
    container_name: web-app
    ports:
      - "5000:80"
    depends_on:
      - grpc-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - GRPC_SERVER_URL=http://grpc-server:5001
    extra_hosts:
      - "grpc-server:192.168.1.150"
  grpc-server:
    build:
      context: ../.
      dockerfile: src/GrpcService/Dockerfile
    container_name: grpc-server
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development